# Generated by Django 4.2.1 on 2023-10-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='imageproj',
            field=models.FileField(null=True, upload_to='proyectos/'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
