# Generated by Django 4.2.6 on 2023-10-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectos', '0003_alter_proyecto_imageproj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='imageproj',
            field=models.FileField(null=True, upload_to='projectos/'),
        ),
    ]
